name = "PermutationSymmetricTensorsDocs" # A unique name for the docs project
uuid = "7f8f492f-359f-45b1-9dc3-067816507f25" # Generate a new UUID for this docs project
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PermutationSymmetricTensors = "22e17884-8c1a-4ea8-8b39-5974e24a9d31"

[compat]
julia = "1.6" 
Documenter = "1" 
PermutationSymmetricTensors = "0.2" #
